/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mythicalmoney;

import org.junit.jupiter.api.Test;

import MythicalMoney.Main;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
