/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MythicalMoney;

import javax.security.auth.login.LoginException;

import MythicalMoney.Data.Setting;
import MythicalMoney.Listeners.Ready;
import MythicalMoney.Listeners.SlashCommand;
import MythicalMoney.Utility.FileUtility;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

public class Main {
    public String getGreeting() {
        return "\nHello World!\n\t- Main.getGreeting";
    }

    public static JDA jda;

    public static void main(String[] args) {
        debug ("Mythical Money is loading...");
        final String token = token ();
        try {
            debug ("Trying to login...");
            jda = JDABuilder.createDefault( token).build ();
            debug ("Finished logging in!");
        } catch (LoginException loginException) {
            debug ("Could not login using this token: \"" + token + "\"");
            return;
        } catch (Exception exception) {
            debug ("An unknown error occured.");
            exception.printStackTrace ();
        }

        {
            Setting.setup ();
        }

        jda.addEventListener (new Ready ());
        jda.addEventListener (new SlashCommand ());
    }

    public static String token () {
        final String token = FileUtility.readFile ("Token.txt");
        if (token.contains ("\n")) {
            return token.substring (0, token.indexOf ("\n"));
        }
        return token;
    }

    public static void debug (final String debug) {
        final String startingString = "\t[Debug] ";

        String formattedDebug = startingString;
        for (int index = 0; index < debug.length (); index++) {
            String character = debug.charAt (index) + "";
            if (character.equals ("\n")) {
                character += startingString;
            }
            formattedDebug += character;
        }
        System.out.println (formattedDebug);
    }
    
    public static void debug (final int debug) {
        debug ("" + debug);
    }

    public static void debug (final long debug) {
        debug ("" + debug);
    }
}
