/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MythicalMoney;

import MythicalMoney.Utility.FileUtility;
import net.dv8tion.jda.api.JDA;

public class Main {
    public static JDA jda;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        debug ("Starting...");
        /*
        try {
            debug ("Trying to login...");
            jda = JDABuilder.createDefault( token ()).build();
            System.out.println ("\tFinished logging in!");
        } catch (LoginException loginException) {
            System.out.println ("Could not login using token: \"" + token () + "\"");
        }

        jda.addEventListener (new ReadyListener ());
        */
    }

    public static String token () {
        String token = FileUtility.readFile ("Token.txt");
        if (token.contains ("\n")) {
            String [] lines = token.split ("\n");
            token = lines [0];
        }
        return token;
    }

    public static void debug (String debug) {
        System.out.println ("\tDebug: \"" + debug + "\"");
    }
    
    public static void debug (int debug) {
        debug ("" + debug);
    }
}
